name: Linter and Container tests

on:
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the current repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Prepare the runner
      - name: Prepare the runner
        run: |
          sudo apt install shellcheck
          sudo npm install -g dockerfile_lint

      # Run the linter tests
      - name: Run linter tests
        run: make

      # Run the container tests for CentOS
      - name: Run CentOS container tests
        run: tests/container-tests.sh centos

      # Run the container tests for Fedora
      - name: Run Fedora container tests
        run: tests/container-tests.sh fedora
